### ISSUE TITLE
[FEATURE]AutoCrystal Sequential ：Calc BetterPlaceRange

### ISSUE THREAD

**Issue by JOniGod** [3arthqu4ke/3arthh4ck#233]
Some servers partch the placement distance of crystals, whether it is the height of Y or the distance of the player
as picture.
![32 DODH4}${L~)5`RE_(7B5](https://user-images.githubusercontent.com/92873946/188580204-0dd6cbbf-e781-4a74-add2-775a29bb2bac.png)
When I stand at the same height as the fakeplayer, the crystal can be placed. This is a problem with the plug-in installed on the 

server, which leads to the need to be at the same height as the player if I want to release a longer distance.
![RIVR`$_Z0DQWVR@PUAD`0PE](https://user-images.githubusercontent.com/92873946/188580455-81ac2c64-c066-4531-9ac9-6351c5db8918.png)

Suggestion: Increase the placement distance of Sequential
How it works: When the calculated crystal position cannot be placed, look for a crystal position that can be placed in the attachment
---------------------------------------------------------------------------------------------------------------------
Example: When my Y axis is different from the enemy, the distance of the crystal I place is 5 (if seq adds betterplace), when seq calculates that the crystal cannot be placed in that position (I set betterplace to 4), it will be placed in the fourth grid Place crystals to kill/pop enemies as much as possible

And can prevent the crystal from being unable to be placed.

**Comment by 3arthqu4ke** [comment]
In the second screenshot it looks like you are actually closer to position. You can debug your distance with BlockHighlight. Turn on distance and check the info in the arraylist. If you want to debug blocks out of range use Reach.

Could you check that you have the same distance to the block with BlockHighlight on multiple Y-Levels?
![2022-09-06_11 10 03](https://user-images.githubusercontent.com/56741599/188595857-f2d2678b-cec5-46de-b045-32dee724a216.png)

In this version https://github.com/3arthqu4ke/3arthh4ck/actions/runs/2994249174 theres also PlaceRangeEyes, which takes the distance from your eyes to the crystal instead of feet and PlaceRangeCenter which takes the distance to the center of the block, maybe those settings help?

**Comment by JOniGod** [comment]
https://streamable.com/fixd0d
watch this maybe give you inspiration
PlaceRangeEyes does the trick, which is really good -> Suggest I think it would be better if you could add range to placerangeeyes
edit:The second picture is indeed a bit biased, my bad

**Comment by Zane2b2t** [comment]
> 

maybe the video is bcs of ur MaxSelfDamage setting

**Comment by JOniGod** [comment]
Not smart advice  I'll close him
