### ISSUE TITLE
[BUG] For god's sake rewrite rotations or fix place rotate making the ca 10x worse

### ISSUE THREAD

**Issue by Zane2b2t** [3arthqu4ke/3arthh4ck#283]
ca is so awsome until u set rotations to place/all

clip at request

**Comment by Zane2b2t** [comment]
also no it's not config issue i tried MANY THINGS and couldn't get it fixed

**Comment by Zane2b2t** [comment]
> What rotate mode do you use?

I tried both smooth and normal will send clip soon:tm:

**Comment by Random3131** [comment]
Wating

**Comment by Zane2b2t** [comment]
> Wating

Soon:tm: remind me in 3 hours

**Comment by Zane2b2t** [comment]
> Wating

me uploada

**Comment by Zane2b2t** [comment]
> > Wating
> 
> me uploada

bruh nvm i dont have clip with rotations lemme redo it

**Comment by Zane2b2t** [comment]
https://streamable.com/v44s9g (Break only not making it worse) (good ca)
https://streamable.com/ltejbo (Place only making it 10x worse) (bad ca) (same as for "all" rotations)

in the first clip crystals get placed while the player goes down in the 2nd one it almost doesn't

**Comment by 3arthqu4ke** [comment]
Are you using MultiThreading? When rotating I would not do that. I also believe Height 0.0 and Place-Height 1.0 are the best values because it makes rotations for placing and breaking identical. You are also using Existed, FocusRotations, Angle 90, idk. When using slow rotations (Place/Break Angle) you might want to extrapolate more?
