### ISSUE TITLE
[FEATURE] Old Plugins Source

### ISSUE THREAD

**Issue by wiiyou** [3arthqu4ke/3arthh4ck#37]
It would be nice if you could put the sources for the old plugins on their own repositories so people in the community can manually fix it. Especially the Baritone plugin because from what I've heard, it uses a modified version of it and it's obfuscated.

**Comment by 3arthqu4ke** [comment]
https://github.com/3arthqu4ke/3arthh4ck/tree/plugins 
Note that the baritone plugin there is not the original version. The only difference to the original version is that this version will probably not work when running the game from an IDE. If you want to the original baritone plugin you need to fork baritone and make it use the normal `'net.minecraftforge.gradle.forge'` gradle plugin instead of `'net.minecraftforge.gradle.tweaker-client'` to compile to searge mappings. I think you might need a reflection hack somewhere else because some class is different with forge but I forgot.

**Comment by wiiyou** [comment]
@3arthqu4ke 

I tried to fix this a while back for fun but it didn't quite work. Although fixing this isn't that important, I would like to know how you made Baritone compile for vanilla mappings nonetheless.

Here's my attempts if you want to see it:

<https://github.com/wiiyou/3arthh4ck/commit/1bd2e4995826223cc15cbb940ddaef295ca5befa>
<https://github.com/wiiyou/baritone/commit/67a54aa104a06bde6525b95c22dd03bb60dd2a62>

**Comment by 3arthqu4ke** [comment]
@wiiyou https://github.com/wiiyou/baritone/pull/1

**Comment by wiiyou** [comment]
Fixed:
https://github.com/wiiyou/3arthh4ck/tree/plugins
https://github.com/wiiyou/baritone/tree/3arthh4ck

**Comment by 3arthqu4ke** [comment]
This https://github.com/wiiyou/baritone/tree/3arthh4ck is on tag 1.2.15?

**Comment by wiiyou** [comment]
Yes, it's on 1.2.15

**Comment by 3arthqu4ke** [comment]
You can make a PR for the plugins branch if you want! I merged the baritone forks already.
