### ISSUE TITLE
[BUG] Placement/Extrapolation error in AutoCrystal

### ISSUE THREAD

**Issue by Random3131** [3arthqu4ke/3arthh4ck#92]
https://streamable.com/ux4fs2
The ca only predicts the position if we are ahead of the enemy and doesn't if we are behind??

**Comment by 3arthqu4ke** [comment]
It still predicts it, symbolized by the small tracer at the fakeplayers feet. I guess it places behind because the position is closer to, you deals the same damage etc., who knows whats going on in the calculations. 

Extrapolation is still being developed. I just had an idea tho, one thing I forgot, good that you remind me.

**Comment by Random3131** [comment]
Btw it also shows NoInterp in the arraylist even tho I have it hidden or even when I turn it off

**Comment by 3arthqu4ke** [comment]
Check the modules in the PB-Gui.

**Comment by Random3131** [comment]
My bad, thanks
